### ISSUE TITLE
installation errors 

### ISSUE THREAD

**Issue by abdulazizalmass** [MohammedAlawami/Saudi-Arabia-COVID-19-Dashboard-Scraping#1]
Greetings

Thank you for the code. I attempted running it over Ubuntu 18 with virtual environment of python 3.6. However, installing the requirements txt was not completed as shown in the link below:
http://imgur.com/gallery/ExnHv84

What do you recommend to resolve the above of you have encountered this before?.

Would you please share your installation environment?

Thanks

**Comment by MohammedAlawami** [comment]
Hello there,
I'm not sure what is causing this issue there, but try upgrading python and pip it might help, or if you have python on your mac try running it there instead of the Ubuntu environment because the issue might be from Ubuntu itself.

**Comment by abdulazizalmass** [comment]
@MohammedAlawami well done. It works :smile:. I am really happy ^_^...nice web scrapping 

I am running Macbook Air 64-bit. 
The fix starting by creating virtualenv:
`virtualenv -p python3.6 moh
Running virtualenv with interpreter /usr/local/bin/python3.6
Already using interpreter /usr/local/opt/python/bin/python3.6
Using base prefix '/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/Omar/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master/moh/bin/python3.6
Also creating executable in /Users/Omar/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master/moh/bin/python
Installing setuptools, pip, wheel...
source moh	bi	done.
(base) Omar@omar:~/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master$ source moh/bin/activate
(moh) (base) Omar@omar:~/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master$ pip3.6 install -r requirements.txt 
Collecting beautifulsoup4==4.9.0
  Using cached beautifulsoup4-4.9.0-py3-none-any.whl (109 kB)
Collecting certifi==2020.4.5.1
  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting et-xmlfile==1.0.1
  Downloading et_xmlfile-1.0.1.tar.gz (8.4 kB)
Collecting idna==2.9
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting jdcal==1.4.1
  Downloading jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)
Collecting numpy==1.18.2
  Downloading numpy-1.18.2-cp36-cp36m-macosx_10_9_x86_64.whl (15.2 MB)
     |████████████████████████████████| 15.2 MB 4.6 MB/s 
Collecting openpyxl==3.0.3
  Using cached openpyxl-3.0.3.tar.gz (172 kB)
Collecting pandas==1.0.3
  Downloading pandas-1.0.3-cp36-cp36m-macosx_10_9_x86_64.whl (10.2 MB)
     |████████████████████████████████| 10.2 MB 9.1 MB/s 
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz==2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting selenium==3.141.0
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting six==1.14.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting soupsieve==2.0
  Using cached soupsieve-2.0-py2.py3-none-any.whl (32 kB)
Collecting urllib3==1.25.8
  Using cached urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
Collecting xlrd==1.2.0
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 4.3 MB/s 
Building wheels for collected packages: et-xmlfile, openpyxl
  Building wheel for et-xmlfile (setup.py) ... done
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8915 sha256=0341a3679680a7efe8d5fc63150b73d8119ee2b2b319ce49e5e0adf515435b26
  Stored in directory: /Users/Omar/Library/Caches/pip/wheels/ef/92/e0/956c00decf3091294b8800d9104f6169a1adacfaafd122ed42
  Building wheel for openpyxl (setup.py) ... done
  Created wheel for openpyxl: filename=openpyxl-3.0.3-py2.py3-none-any.whl size=241262 sha256=2073f9bff941fbb7913c954780e75084655279e3e2af172a4ee4ac587b182feb
  Stored in directory: /Users/Omar/Library/Caches/pip/wheels/a2/97/2a/d5e43384faa87a34b198b8d75e03e7130e70321ea446f98703
Successfully built et-xmlfile openpyxl
Installing collected packages: soupsieve, beautifulsoup4, certifi, chardet, et-xmlfile, idna, jdcal, numpy, openpyxl, six, python-dateutil, pytz, pandas, urllib3, selenium, xlrd
Successfully installed beautifulsoup4-4.9.0 certifi-2020.4.5.1 chardet-3.0.4 et-xmlfile-1.0.1 idna-2.9 jdcal-1.4.1 numpy-1.18.2 openpyxl-3.0.3 pandas-1.0.3 python-dateutil-2.8.1 pytz-2019.3 selenium-3.141.0 six-1.14.0 soupsieve-2.0 urllib3-1.25.8 xlrd-1.2.0
(moh) (base) Omar@omar:~/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master$ python dashboard_scraper.py
1%  Traceback (most recent call last):
  File "/Users/Omar/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master/moh/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './chromedriver': './chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dashboard_scraper.py", line 14, in <module>
    driver = webdriver.Chrome('./chromedriver')
  File "/Users/Omar/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master/moh/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Users/Omar/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master/moh/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

(moh) (base) Omar@omar:~/Desktop/DataScience/moh/Saudi-Arabia-COVID-19-Dashboard-Scraping-master$ python dashboard_scraper.py
100% 
Finished Scraping, the file ksa_covid19.xlsx has been updated.(moh) (base) Omar@-Scraping-master$ aScience/moh/Saudi-Arabia-COVID-19-Dashboard-
`
